const dropDown = require("./modules/dropdown");
const popupMenu = require("./modules/popup-menu");
const phoneMask = require("./modules/phone-mask");
const formSubmit = require("./modules/form-submit");
const formulaPopup = require("./modules/formula-popup");
const formulaSlider = require("./modules/formula-slider");
const repairTypesTabs = require("./modules/repair-types-tabs");
const portfolioSlider = require("./modules/portfolio-slider");
const transparencySlider = require("./modules/transparency-slider");
const reviewsSlider = require("./modules/reviews-slider");
const accordion = require("./modules/accordion");
const repairTypesPopup = require("./modules/repair-types-popup");

dropDown();
popupMenu();
phoneMask();
formSubmit();
formulaPopup();
formulaSlider();
repairTypesTabs();
portfolioSlider();
transparencySlider();
reviewsSlider();
accordion();
repairTypesPopup();
