name: Deploy Webpack Project (SSH)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Webpack project
        run: npm run build

      - name: Deploy via rsync over SSH
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: pagelist_ru_usr
          remote_port: 22
          path: dist/
          remote_path: /var/www/pagelist_ru_usr/data/www/pagelist.ru/diploma/
          switches: -rlgoDzvO --delete
