name: Deploy Webpack Project (SSH)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Webpack project
        run: npm run build

      - name: Deploy via rsync over SSH
        uses: Burnett01/rsync-deployments@7.0.1  # Используем стабильный и гибкий инструмент
        with:
          TEMPLATE: linux-node
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: pagelist_ru_usr
          TARGET: /var/www/pagelist_ru_usr/data/www/pagelist.ru/diploma/
          SOURCE: dist/
          ARGS: -rlgoDzvO --delete
